import { wordList } from "./words";

export type Category = "general" | "chess" | "animals" | "food";

export interface CategoryConfig {
  label: string;
  description: string;
  words: string[];
  wordDescriptions: Record<string, string>;
}

// ─── Chess ────────────────────────────────────────────────────────────────────

const chessWords: string[] = [
  // 4-letter
  "king", "pawn", "rook", "fork", "draw", "rank", "file", "mate", "game", "move",
  "play", "open", "push", "trap", "plan", "time", "risk", "turn", "back", "dark",
  "edge", "gain", "pull", "line",
  // 5-letter
  "queen", "chess", "check", "board", "black", "white", "piece", "trade", "tempo",
  "blitz", "tower", "flank", "space",
  // 6-letter
  "bishop", "castle", "gambit", "knight", "resign", "attack", "defend", "center",
  "square", "tactic", "passed",
  // 7-letter
  "endgame", "opening", "capture", "promote", "advance", "defense", "blunder", "develop",
  // 8-letter
  "castling", "diagonal", "position", "tactical", "strategy", "exchange", "sicilian",
  "zugzwang",
];

const chessDescriptions: Record<string, string> = {
  king:     "The most important piece; the game ends when it is checkmated.",
  pawn:     "The most numerous piece, capable of promoting to any piece upon reaching the far rank.",
  rook:     "A powerful piece that moves any number of squares horizontally or vertically.",
  fork:     "A tactic where one piece simultaneously attacks two enemy pieces.",
  draw:     "A result where neither player wins, often agreed upon or reached by stalemate.",
  rank:     "A horizontal row of squares across the board, numbered 1 through 8.",
  file:     "A vertical column of squares on the board, labeled a through h.",
  mate:     "Short for checkmate; the king is in check with no legal escape.",
  game:     "A single contest of chess between two players.",
  move:     "A player's turn to transfer a piece to another square on the board.",
  play:     "The act of making moves and decisions throughout a chess game.",
  open:     "A position where central pawns have been exchanged, opening lines for pieces.",
  push:     "To advance a pawn forward on the board.",
  trap:     "A sequence of moves designed to lure the opponent into a losing line.",
  plan:     "A strategic idea or series of moves aimed at a specific goal.",
  time:     "The clock allocation each player has to complete their moves.",
  risk:     "The chance of losing material or positional ground in exchange for an attack.",
  turn:     "Each player's opportunity to make one move in alternating sequence.",
  back:     "Moving a piece toward one's own side of the board.",
  dark:     "The color of alternating squares, generally less favorable for knights on the edge.",
  edge:     "The border files or ranks of the board, typically poor squares for knights.",
  gain:     "To win material or positional advantage over the opponent.",
  pull:     "To draw a piece toward the center or a more active square.",
  line:     "An open file or diagonal that provides movement paths for pieces.",
  queen:    "The most powerful piece, moving any number of squares in any direction.",
  chess:    "A two-player strategy board game played on an 8×8 grid of 64 squares.",
  check:    "A direct attack on the king that must be resolved on the very next move.",
  board:    "The 8×8 grid of 64 alternating light and dark squares where the game is played.",
  black:    "The second player to move, playing with the darker-colored pieces.",
  white:    "The first player to move, playing with the lighter-colored pieces.",
  piece:    "Any of the six unit types: king, queen, rook, bishop, knight, or pawn.",
  trade:    "To exchange one piece for an opponent's piece of similar value.",
  tempo:    "A unit of time; losing a tempo means wasting a move and falling behind.",
  blitz:    "A fast time-control format where each player typically has five minutes or less.",
  tower:    "An alternative name for the rook, still used in many European languages.",
  flank:    "The sides of the board, either the queenside (a-d files) or kingside (e-h files).",
  space:    "Control over squares, giving pieces more room to maneuver and restrict the opponent.",
  bishop:   "A piece that moves diagonally any number of squares, staying on one color forever.",
  castle:   "To move the king and rook simultaneously in a special defensive maneuver.",
  gambit:   "An opening where material is sacrificed early to gain positional compensation.",
  knight:   "The only piece that can jump over others, moving in an L-shape.",
  resign:   "To concede defeat voluntarily without being checkmated.",
  attack:   "An aggressive sequence of moves aimed at the opponent's king or pieces.",
  defend:   "To protect pieces or the king from an opponent's active threats.",
  center:   "The four central squares; controlling them is often decisive in the middlegame.",
  square:   "One of the 64 individual cells on the chess board.",
  tactic:   "A short forced sequence of moves that yields a concrete advantage.",
  passed:   "A pawn with no opposing pawns blocking or guarding its path to promotion.",
  endgame:  "The final phase when few pieces remain, often decided by king activity and pawns.",
  opening:  "The initial phase where pieces are developed and the center is contested.",
  capture:  "To remove an opponent's piece from the board by moving onto its square.",
  promote:  "To replace a pawn that reaches the last rank with a more powerful piece.",
  advance:  "To push a pawn toward the opponent's side of the board.",
  defense:  "A system or strategy played by the second player to counter the opponent's opening.",
  blunder:  "A serious mistake that significantly worsens one's position, often losing material.",
  develop:  "To move pieces from their starting squares to more active positions early in the game.",
  castling: "The special king-and-rook maneuver that brings the king to safety behind pawns.",
  diagonal: "A line of same-colored squares stretching across the board at an angle.",
  position: "The arrangement of all pieces on the board at any given moment.",
  tactical: "Relating to short-term combinations involving direct threats and concrete calculation.",
  strategy: "The long-term plan guiding piece placement, pawn structure, and king safety.",
  exchange: "Trading a rook for a minor piece, or more broadly swapping equal material.",
  sicilian: "A popular aggressive defense for Black beginning with 1...c5.",
  zugzwang: "A situation where every available move worsens the player's own position.",
};

// ─── Animals ──────────────────────────────────────────────────────────────────

const animalWords: string[] = [
  // 4-letter
  "bear", "bird", "bull", "calf", "clam", "crab", "crow", "deer", "duck", "fawn",
  "fish", "flea", "frog", "gull", "hare", "hawk", "kite", "lamb", "lion", "lynx",
  "mole", "moth", "mule", "newt", "slug", "swan", "toad", "wasp", "wolf", "wren",
  "goat", "seal", "mink", "vole",
  // 5-letter
  "bison", "cobra", "crane", "dingo", "eagle", "finch", "gecko", "goose", "heron",
  "hippo", "horse", "hyena", "koala", "llama", "moose", "mouse", "otter", "panda",
  "quail", "raven", "shark", "sheep", "shrew", "skunk", "sloth", "snail", "snake",
  "tapir", "tiger", "viper", "whale", "zebra", "trout", "squid", "stork", "snipe",
  // 6-letter
  "badger", "beaver", "canary", "cougar", "coyote", "donkey", "falcon", "ferret",
  "gibbon", "gopher", "iguana", "jaguar", "lizard", "magpie", "marmot", "monkey",
  "osprey", "parrot", "pigeon", "rabbit", "salmon", "toucan", "weasel", "condor",
  "mussel", "oyster", "locust", "mantis",
  // 7-letter
  "buffalo", "buzzard", "caribou", "catfish", "dolphin", "hamster", "herring",
  "lobster", "pelican", "penguin", "piranha", "raccoon", "sparrow", "vulture",
  "warthog", "wallaby",
  // 8-letter
  "bluebird", "cardinal", "chipmunk", "flamingo", "hedgehog", "kangaroo",
  "parakeet", "pheasant", "platypus", "seahorse", "starfish", "tortoise", "aardvark",
];

const animalDescriptions: Record<string, string> = {
  bear:     "A large omnivorous mammal known for its thick fur and powerful build.",
  bird:     "A warm-blooded vertebrate with feathers, wings, and a beak.",
  bull:     "An adult male bovine often associated with strength and stubbornness.",
  calf:     "The young offspring of a cow or other large animal such as a whale.",
  clam:     "A bivalve mollusk that lives buried in sand or mud near shorelines.",
  crab:     "A crustacean with a broad shell and ten legs, including two claws.",
  crow:     "A highly intelligent black bird known for its remarkable problem-solving abilities.",
  deer:     "A graceful hoofed mammal whose males typically bear antlers each season.",
  duck:     "A waterbird with a flat bill, webbed feet, and waterproof feathers.",
  fawn:     "A newborn or very young deer, typically spotted for camouflage in vegetation.",
  fish:     "An aquatic vertebrate with gills, fins, and typically a scaly body.",
  flea:     "A tiny wingless insect that feeds on blood and can jump enormous distances relative to its size.",
  frog:     "An amphibian with strong hind legs for jumping and smooth, moist skin.",
  gull:     "A coastal seabird known for its scavenging habits and loud, familiar calls.",
  hare:     "A fast-running mammal similar to a rabbit but with longer ears and hind legs.",
  hawk:     "A sharp-eyed bird of prey renowned for its speed and precise aerial hunting.",
  kite:     "A graceful bird of prey often seen soaring and circling on warm air thermals.",
  lamb:     "A young sheep, widely used as a symbol of innocence and gentleness.",
  lion:     "A large social cat that lives in groups called prides, native to Africa.",
  lynx:     "A secretive wild cat with tufted ears and large padded paws suited for snow.",
  mole:     "A small burrowing mammal with velvety fur and tiny eyes adapted for underground life.",
  moth:     "A nocturnal insect related to the butterfly, often attracted to artificial light.",
  mule:     "A hybrid offspring of a donkey and a horse, renowned for its endurance.",
  newt:     "A small semi-aquatic salamander with the remarkable ability to regenerate lost limbs.",
  slug:     "A soft-bodied gastropod that moves on a muscular foot leaving a glistening slime trail.",
  swan:     "A large, graceful waterbird renowned for its elegance and tendency to pair for life.",
  toad:     "A rough-skinned amphibian that lives mostly on land and returns to water to breed.",
  wasp:     "A stinging insect with a narrow waist that, unlike bees, can sting multiple times.",
  wolf:     "A social apex predator and the largest wild member of the dog family.",
  wren:     "A tiny, energetic songbird with a surprisingly loud voice for its small size.",
  goat:     "A hardy domestic animal known for its curiosity and ability to eat almost anything.",
  seal:     "An aquatic mammal with flippers that is agile in water but clumsy on land.",
  mink:     "A small semi-aquatic mammal with luxuriously dense, water-resistant fur.",
  vole:     "A small rodent resembling a mouse that lives in meadows and woodland edges.",
  bison:    "The largest land animal in North America, also known as the American buffalo.",
  cobra:    "A venomous snake capable of spreading a wide hood around its neck when threatened.",
  crane:    "A tall wading bird renowned for its elaborate courtship dances.",
  dingo:    "Australia's wild dog, believed to have arrived with ancient human settlers.",
  eagle:    "A large, powerful bird of prey and a universal symbol of strength and freedom.",
  finch:    "A small seed-eating songbird with a short, strong, conical bill.",
  gecko:    "A small lizard known for its ability to climb smooth vertical surfaces.",
  goose:    "A large waterbird related to the duck that can be famously territorial.",
  heron:    "A tall wading bird that stands perfectly motionless while waiting to spear fish.",
  hippo:    "One of the heaviest land animals, spending most of each day cooling in water.",
  horse:    "A domesticated mammal used for riding, racing, and farm work for thousands of years.",
  hyena:    "A carnivore with a distinctive laugh-like call that lives in Africa and Asia.",
  koala:    "An Australian marsupial that sleeps up to 22 hours a day and feeds only on eucalyptus.",
  llama:    "A South American camelid used as a pack animal and valued for its soft wool.",
  moose:    "The largest member of the deer family, bearing broad, palmate antlers.",
  mouse:    "A small rodent and one of the most widespread mammals on Earth.",
  otter:    "A playful semi-aquatic mammal known for floating on its back and using tools to open shellfish.",
  panda:    "A bear native to China that eats almost exclusively bamboo shoots and leaves.",
  quail:    "A small ground-dwelling bird that prefers to run rather than take flight.",
  raven:    "A large, all-black bird famed for its intelligence and deep association with mythology.",
  shark:    "An apex predator of the ocean with a powerful sense of smell and rows of sharp teeth.",
  sheep:    "A domesticated ruminant raised worldwide for wool, meat, and milk.",
  shrew:    "One of the world's smallest mammals, with an extremely high metabolism requiring near-constant eating.",
  skunk:    "A mammal famous for spraying a powerful, pungent odor as a defense against predators.",
  sloth:    "The world's slowest mammal, hanging motionless from rainforest trees for most of its life.",
  snail:    "A mollusk that carries a spiral shell on its back and moves at a famously slow pace.",
  snake:    "A legless reptile that moves by undulation and swallows prey whole.",
  tapir:    "A large herbivore with a flexible prehensile snout, distantly related to horses and rhinos.",
  tiger:    "The largest wild cat, instantly recognizable by its orange coat with bold black stripes.",
  viper:    "A venomous snake with hinged hollow fangs that fold back when not in use.",
  whale:    "The largest animal ever known to have existed, a fully aquatic marine mammal.",
  zebra:    "An African equid instantly recognizable by its unique black-and-white striped coat.",
  trout:    "A freshwater fish of the salmon family, prized by anglers for its fighting spirit.",
  squid:    "A fast-swimming cephalopod with ten limbs and the ability to squirt ink to escape predators.",
  stork:    "A large wading bird with long legs and a long bill, traditionally linked to delivering babies.",
  snipe:    "A wading bird with a very long bill, so elusive that hunters gave rise to the term 'sniper'.",
  badger:   "A burrowing mammal with a distinctive black-and-white striped head.",
  beaver:   "A semi-aquatic rodent famous for felling trees and building impressive dams.",
  canary:   "A small songbird from the Canary Islands widely kept as a pet for its cheerful song.",
  cougar:   "A large wild cat of the Americas, also known as a mountain lion or puma.",
  coyote:   "A highly adaptable North American canid that thrives in wild and urban habitats alike.",
  donkey:   "A domesticated member of the horse family used as a working animal worldwide.",
  falcon:   "A fast-flying bird of prey celebrated for its breathtaking high-speed diving stoop.",
  ferret:   "A domesticated carnivore related to weasels, kept as a pet or used in rabbit hunting.",
  gibbon:   "A small ape with extremely long arms that swings through trees with remarkable agility.",
  gopher:   "A burrowing rodent known for creating extensive underground tunnel networks.",
  iguana:   "A large tropical lizard that is herbivorous and an excellent swimmer.",
  jaguar:   "The largest cat in the Americas, famous for its powerful bite and love of swimming.",
  lizard:   "A reptile with four legs, a long tail, and scaly skin, found on every continent but Antarctica.",
  magpie:   "A bold black-and-white bird from the crow family, long rumored to be attracted to shiny objects.",
  marmot:   "A large ground squirrel that hibernates through winter in mountainous regions.",
  monkey:   "A primate with a tail, known for its curiosity, social behavior, and use of tools.",
  osprey:   "A fish-eating hawk that plunges feet-first into water with impressive precision to catch prey.",
  parrot:   "A colorful bird famous for its ability to mimic human speech and complex sounds.",
  pigeon:   "A common urban bird with an extraordinary inborn sense of direction.",
  rabbit:   "A small burrowing mammal with long ears and powerful hind legs built for speed.",
  salmon:   "An anadromous fish that migrates from the ocean upstream to freshwater to breed.",
  toucan:   "A tropical bird of Central and South America with a colorful, oversized beak.",
  weasel:   "A slender, agile predator known for squeezing into tiny spaces to pursue prey.",
  condor:   "One of the world's largest flying birds, a soaring scavenger of the Americas.",
  mussel:   "A bivalve mollusk that anchors itself to rocks with strong thread-like fibers.",
  oyster:   "A bivalve mollusk capable of producing pearls and highly prized as a seafood.",
  locust:   "A swarming grasshopper that forms massive groups capable of devastating entire crops.",
  mantis:   "A predatory insect that ambushes prey with lightning-fast spiked forelegs.",
  buffalo:  "A large bovine—either the American bison or the formidable African cape buffalo.",
  buzzard:  "A broad-winged bird of prey that soars effortlessly on rising warm air thermals.",
  caribou:  "A migratory deer of the Arctic tundra, also known in Europe as the reindeer.",
  catfish:  "A bottom-dwelling freshwater fish named for its long whisker-like sensory barbels.",
  dolphin:  "A highly intelligent, social marine mammal renowned for its playful leaping and complex communication.",
  hamster:  "A small burrowing rodent with expandable cheek pouches designed to carry large amounts of food.",
  herring:  "A small, oily ocean fish that swims in enormous silvery schools in cold waters.",
  lobster:  "A large marine crustacean with a hard shell and claws, considered a luxury seafood.",
  pelican:  "A large water bird with a distinctive expandable throat pouch used to scoop up fish.",
  penguin:  "A flightless bird perfectly adapted to swimming in the cold waters of the Southern Hemisphere.",
  piranha:  "A freshwater fish of South America with razor-sharp interlocking teeth.",
  raccoon:  "A North American mammal easily recognized by its black eye mask and ringed tail.",
  sparrow:  "A small, hardy songbird that thrives in close proximity to human settlements worldwide.",
  vulture:  "A soaring scavenger bird with a bare head adapted to feeding safely on carcasses.",
  warthog:  "An African wild pig with distinctive curved tusks and prominent facial warts.",
  wallaby:  "An Australian marsupial closely related to the kangaroo but considerably smaller.",
  bluebird: "A small North American thrush prized by birders for its vivid sky-blue plumage.",
  cardinal: "A North American songbird where the crested male displays a brilliant scarlet-red color.",
  chipmunk: "A small, striped ground squirrel famous for stuffing its cheek pouches with food.",
  flamingo: "A wading bird known for its striking pink plumage and distinctive one-legged stance.",
  hedgehog: "A small spiny mammal that instinctively rolls into a tight protective ball when threatened.",
  kangaroo: "Australia's iconic marsupial that hops on powerful hind legs and carries young in a pouch.",
  parakeet: "A small, slender parrot often kept as a beloved pet for its playful, sociable nature.",
  pheasant: "A large, colorful game bird with an extravagant long tail, introduced to many parts of the world.",
  platypus: "A semi-aquatic mammal with a duck-like bill, beaver-like tail, and venom-injecting heel spurs.",
  seahorse: "A tiny upright-swimming fish where the male, uniquely, carries and gives birth to the young.",
  starfish: "A marine invertebrate with typically five arms that can slowly regenerate any lost limb.",
  tortoise: "A slow-moving land reptile enclosed in a domed shell, some species living for over 150 years.",
  aardvark: "A nocturnal African mammal that uses its elongated snout and sticky tongue to eat ants and termites.",
};

// ─── Food ─────────────────────────────────────────────────────────────────────

const foodWords: string[] = [
  // 4-letter
  "beef", "beet", "cake", "clam", "corn", "crab", "duck", "fish", "hash", "kale",
  "kiwi", "lamb", "lard", "leek", "lime", "mint", "okra", "oats", "pear", "plum",
  "pork", "rice", "sage", "salt", "taco", "tart", "tofu", "tuna", "veal", "yams",
  "wine", "milk", "nuts",
  // 5-letter
  "bacon", "basil", "berry", "broth", "chili", "clove", "cocoa", "cream", "crepe",
  "curry", "feast", "grits", "guava", "herbs", "honey", "kebab", "lemon", "liver",
  "mango", "melon", "mocha", "olive", "onion", "pasta", "patty", "peach", "pecan",
  "pesto", "pizza", "prawn", "puree", "ramen", "roast", "salad", "sauce", "scone",
  "spice", "squid", "steak", "sugar", "syrup", "taffy", "thyme", "toast", "torte",
  "trout", "tuber", "wafer", "wheat", "yeast",
  // 6-letter
  "almond", "banana", "batter", "butter", "carrot", "cashew", "celery", "cereal",
  "cheese", "cherry", "chives", "citrus", "cookie", "fennel", "fondue", "garlic",
  "ginger", "grapes", "lentil", "litchi", "muffin", "nectar", "nougat", "nutmeg",
  "oyster", "papaya", "pepper", "pickle", "ragout", "raisin", "savory", "shrimp",
  "sorbet", "sponge", "squash", "toffee", "tomato", "turnip", "waffle", "walnut",
  "yogurt",
  // 7-letter
  "avocado", "brisket", "burrito", "calzone", "cassava", "chutney", "cobbler",
  "compote", "crouton", "custard", "fritter", "granola", "lasagna", "lettuce",
  "mustard", "oatmeal", "pancake", "paprika", "parsley", "poultry", "pretzel",
  "pudding", "saffron", "sardine", "sausage", "seafood", "sherbet", "sirloin",
  "souffle", "spinach", "strudel", "tapioca", "truffle", "vanilla", "vinegar",
  // 8-letter
  "allspice", "barbecue", "baguette", "broccoli", "cinnamon", "coleslaw",
  "couscous", "cucumber", "eggplant", "gazpacho", "mackerel", "meatball",
  "molasses", "mushroom", "parmesan", "plantain", "porridge", "rosemary",
  "tarragon", "tiramisu", "turmeric", "zucchini",
];

const foodDescriptions: Record<string, string> = {
  beef:     "Meat from cattle, a protein-rich staple found in cuisines around the world.",
  beet:     "A root vegetable with a deep red color, sweet earthy flavor, and vivid juice.",
  cake:     "A sweet baked dessert made from flour, sugar, eggs, and fat, often frosted.",
  clam:     "A bivalve shellfish with a briny, sweet flavor popular in chowder and pasta.",
  corn:     "A cereal grain grown worldwide, eaten fresh on the cob, dried, or ground into meal.",
  crab:     "A crustacean with sweet, delicate meat that is prized in coastal cuisines.",
  duck:     "Poultry with rich, flavorful dark meat often slow-roasted or braised.",
  fish:     "An aquatic animal that provides lean protein in countless dishes across every culture.",
  hash:     "A dish of diced cooked meat and vegetables fried together, often served at breakfast.",
  kale:     "A nutrient-dense leafy green with a hearty, slightly bitter, earthy taste.",
  kiwi:     "A small brown fruit with bright green flesh and a tangy, tropical flavor.",
  lamb:     "Meat from a young sheep, prized for its tender texture and mild, distinctive flavor.",
  lard:     "Rendered pig fat once widely used in baking for its ability to produce a flaky, rich pastry.",
  leek:     "A mild-flavored vegetable related to the onion, essential in soups, stews, and pies.",
  lime:     "A tart citrus fruit indispensable in cocktails, marinades, and tropical dishes.",
  mint:     "An aromatic herb used to add a cool, refreshing flavor to food, drinks, and desserts.",
  okra:     "A green pod vegetable that acts as a natural thickener in stews and gumbo dishes.",
  oats:     "A cereal grain eaten as porridge or used in baking for a hearty, wholesome texture.",
  pear:     "A sweet, juicy fruit with soft, melting flesh and a subtly grainy texture.",
  plum:     "A stone fruit with juicy, sweet flesh ranging in color from yellow to deep purple.",
  pork:     "Meat from pigs, the single most widely consumed meat in the world.",
  rice:     "A cereal grain that is the primary food staple for more than half the world's population.",
  sage:     "An aromatic herb with a savory, slightly peppery flavor central to stuffings and sauces.",
  salt:     "A mineral that enhances flavor and has been used to preserve food for thousands of years.",
  taco:     "A Mexican dish consisting of a folded tortilla filled with meat, cheese, and various toppings.",
  tart:     "A pastry with an open, crisp shell filled with sweet fruit, custard, or savory ingredients.",
  tofu:     "A plant-based protein made from curdled soy milk, used widely across Asian cuisines.",
  tuna:     "A large ocean fish prized for its firm, meaty flesh, eaten raw in sushi or canned.",
  veal:     "Meat from a young calf, known for its very pale color and delicate, mild flavor.",
  yams:     "Starchy root vegetables with a denser, earthier flavor than sweet potatoes.",
  wine:     "An alcoholic beverage made from fermented grapes, paired thoughtfully with food worldwide.",
  milk:     "A nutrient-rich liquid produced by mammals that forms the base of all dairy products.",
  nuts:     "Edible seeds with a hard shell, rich in healthy fats, protein, and deep flavor.",
  bacon:    "Cured and smoked strips of pork belly, a universally beloved breakfast staple.",
  basil:    "A fragrant herb with a sweet, slightly peppery flavor that is central to Italian cooking.",
  berry:    "A small, juicy fruit packed with antioxidants, fiber, and natural sweetness.",
  broth:    "A flavorful liquid made by simmering meat, bones, or vegetables, the foundation of soups.",
  chili:    "A spiced stew of meat and chili peppers, a cornerstone of Tex-Mex and Mexican cooking.",
  clove:    "A dried aromatic flower bud with a warm, pungent flavor used in baking and spice blends.",
  cocoa:    "Powdered processed cacao bean, the key ingredient in chocolate, baking, and hot drinks.",
  cream:    "The high-fat layer skimmed from milk, used to enrich sauces, soups, and desserts.",
  crepe:    "A thin, delicate French pancake served with sweet or savory fillings.",
  curry:    "A spiced dish central to South and Southeast Asian cooking with countless regional variations.",
  feast:    "A large, elaborate meal shared by many people to celebrate a special occasion.",
  grits:    "A Southern US staple of coarsely ground boiled corn, often served with butter or cheese.",
  guava:    "A tropical fruit with fragrant pink flesh and a sweet, floral, slightly tart flavor.",
  herbs:    "Aromatic plants used fresh or dried to season, garnish, and elevate the flavor of food.",
  honey:    "A sweet, viscous syrup produced by bees from flower nectar with a complex, variable flavor.",
  kebab:    "Seasoned meat or vegetables threaded onto a skewer and grilled over open flame.",
  lemon:    "A sour citrus fruit whose bright juice and fragrant zest elevate both savory and sweet dishes.",
  liver:    "The nutrient-dense organ meat of animals, exceptionally rich in iron and vitamins.",
  mango:    "A tropical stone fruit renowned for its intensely sweet, fragrant, and juicy orange flesh.",
  melon:    "A large, juicy fruit with high water content and mild sweetness, popular in warm climates.",
  mocha:    "A coffee drink blending rich espresso with chocolate, or a flavor combining both.",
  olive:    "A small fruit cured in brine or cold-pressed into oil, central to Mediterranean cooking.",
  onion:    "A pungent allium vegetable that forms the aromatic flavor base of countless dishes worldwide.",
  pasta:    "An Italian staple made from durum wheat dough, shaped into hundreds of distinct forms.",
  patty:    "A flat, shaped portion of seasoned ground meat or vegetables, ready for grilling.",
  peach:    "A soft stone fruit with sweet, fragrant flesh and a distinctive velvety skin.",
  pecan:    "A buttery, richly flavored nut native to North America, beloved in pies and pralines.",
  pesto:    "An Italian sauce of fresh basil, pine nuts, garlic, parmesan, and olive oil.",
  pizza:    "An Italian flatbread topped with tomato sauce, cheese, and an array of toppings.",
  prawn:    "A large shrimp prized for its naturally sweet flavor and firm, juicy texture.",
  puree:    "A smooth, creamy paste made by blending and straining cooked fruit or vegetables.",
  ramen:    "A Japanese noodle soup with a deeply flavored broth and varied toppings.",
  roast:    "Meat or vegetables cooked in a hot oven with dry heat to develop a caramelized crust.",
  salad:    "A cold dish of raw or lightly cooked ingredients tossed with a seasoned dressing.",
  sauce:    "A liquid or semi-liquid condiment that adds moisture, richness, and flavor to a dish.",
  scone:    "A lightly sweetened quick bread, served with clotted cream and jam in British tradition.",
  spice:    "A dried aromatic plant product used to season and perfume food with bold, complex flavors.",
  squid:    "A cephalopod with tender flesh enjoyed fried, grilled, or tossed with pasta.",
  steak:    "A thick slice of beef, typically grilled or pan-seared, the centerpiece of a classic meal.",
  sugar:    "A crystalline carbohydrate extracted from cane or beet that sweetens and preserves food.",
  syrup:    "A thick, sweet liquid made by dissolving sugar in water or extracted directly from plants.",
  taffy:    "A chewy, stretchy candy made by repeatedly pulling molten sugar until light and airy.",
  thyme:    "A fragrant herb with tiny aromatic leaves, essential in Mediterranean and French cooking.",
  toast:    "Bread browned by dry heat, the versatile base for an enormous variety of toppings.",
  torte:    "A rich, dense, flourless cake made with ground nuts or breadcrumbs.",
  trout:    "A freshwater fish with delicate pink or white flesh, often pan-fried, smoked, or baked.",
  tuber:    "A swollen underground plant stem such as a potato, a global staple energy source.",
  wafer:    "A thin, very crisp, and delicate biscuit used as a base for ice cream and chocolate bars.",
  wheat:    "The world's most widely cultivated cereal grain, milled into flour for bread and pasta.",
  yeast:    "A living microorganism that ferments sugars to produce carbon dioxide, making dough rise.",
  almond:   "A tree nut with a mild, sweet flavor widely used in baking, snacking, and plant-based milk.",
  banana:   "A sweet, creamy tropical fruit that is one of the most produced and eaten foods on Earth.",
  batter:   "A thick liquid mixture of flour, eggs, and milk used to coat food for frying or baking.",
  butter:   "Churned cream solidified into a rich, golden fat essential in cooking and baking.",
  carrot:   "An orange root vegetable with a naturally sweet flavor enjoyed raw, roasted, or juiced.",
  cashew:   "A kidney-shaped nut with a mild, creamy flavor native to coastal Brazil.",
  celery:   "A crisp, low-calorie vegetable with a mild flavor used raw as a snack or in soups.",
  cereal:   "A grain-based food processed into flakes or puffs and eaten with milk for breakfast.",
  cheese:   "A dairy product made by curdling and aging milk, ranging from soft brie to hard parmesan.",
  cherry:   "A small stone fruit with a satisfying tart-sweet flavor, eaten fresh or used in desserts.",
  chives:   "A mild herb in the onion family with a delicate flavor, often used as a garnish.",
  citrus:   "A family of acidic, vitamin C-rich fruits including lemons, oranges, limes, and grapefruits.",
  cookie:   "A small, flat, sweet baked treat enjoyed the world over as a snack or dessert.",
  fennel:   "A bulb vegetable with a mild anise-like flavor, eaten raw in salads or slow-roasted.",
  fondue:   "A Swiss dish of melted cheese or chocolate kept warm for dipping bread or fruit.",
  garlic:   "A pungent bulb used to add a deep, savory flavor to dishes across every world cuisine.",
  ginger:   "A spicy, aromatic root used fresh, dried, pickled, or candied in cooking and drinks.",
  grapes:   "Small, juicy fruits eaten fresh, dried into raisins, or fermented to make wine.",
  lentil:   "A high-protein legume that is a dietary cornerstone in soups, stews, and salads worldwide.",
  litchi:   "A tropical fruit with perfumed, translucent white flesh beneath a rough red shell.",
  muffin:   "A small, domed quick bread or yeast roll, often sweet and eaten at breakfast.",
  nectar:   "A sweet liquid produced by flowers, also used to describe rich, sweet fruit drinks.",
  nougat:   "A chewy, airy confection made from sugar, honey, egg whites, and often nuts.",
  nutmeg:   "A warm, gently sweet spice ground from the seed of a tropical evergreen tree.",
  oyster:   "A briny, mineral-rich bivalve shellfish eaten raw on the half-shell or fried.",
  papaya:   "A tropical fruit with vibrant orange flesh and a mild, honey-like sweetness.",
  pepper:   "A versatile spice or vegetable ranging from mild sweet bell to fiery hot chili.",
  pickle:   "A vegetable, most often cucumber, preserved in brine or vinegar for a sharp, tangy flavor.",
  ragout:   "A rich French slow-cooked stew of braised meat and vegetables in a thick sauce.",
  raisin:   "A dried grape with concentrated, jammy sweetness used in baking and trail mix.",
  savory:   "A fragrant herb with a slightly peppery, thyme-like flavor, traditionally paired with beans.",
  shrimp:   "A small crustacean with sweet, tender meat, one of the most widely eaten seafoods in the world.",
  sorbet:   "A light, refreshing frozen dessert made entirely from sweetened fruit juice or puree.",
  sponge:   "A light, airy cake made by whipping eggs with sugar and gently folding in flour.",
  squash:   "A versatile vegetable family ranging from tender summer zucchini to dense butternut.",
  toffee:   "A hard, glossy candy made by caramelizing butter and sugar together until brittle.",
  tomato:   "A red, juicy fruit used as a vegetable, the cornerstone of sauces and salads worldwide.",
  turnip:   "A round root vegetable with a mildly bitter, peppery flavor used in soups and stews.",
  waffle:   "A batter-based food cooked in a ridged iron mold to create a crisp, pocketed surface.",
  walnut:   "A richly flavored nut with a slightly bitter finish, used in baking, salads, and sauces.",
  yogurt:   "Fermented milk with a creamy, tangy flavor, eaten plain or with fruit and granola.",
  avocado:  "A creamy, green-fleshed fruit high in healthy fats and the key ingredient in guacamole.",
  brisket:  "A tough cut of beef from the chest that becomes meltingly tender through slow smoking or braising.",
  burrito:  "A Mexican flour tortilla tightly wrapped around a filling of rice, beans, meat, and salsa.",
  calzone:  "An Italian folded pizza sealed like a half-moon and baked until the dough is golden.",
  cassava:  "A starchy tropical root and the source of tapioca, a caloric staple across Africa and Asia.",
  chutney:  "A sweet, spiced condiment made from cooked fruit or vegetables with vinegar and sugar.",
  cobbler:  "A rustic baked dessert with a bubbling fruit filling topped with thick, biscuit-like dough.",
  compote:  "A French dessert of whole or cut fruit gently simmered in a light sugar syrup.",
  crouton:  "A small cube of toasted or pan-fried bread added to salads and soups for crunch.",
  custard:  "A smooth, rich sauce or dessert made from eggs and cream or milk, thickened by gentle heat.",
  fritter:  "A piece of fruit, meat, or vegetable dipped in batter and deep-fried until golden.",
  granola:  "A crunchy breakfast mixture of rolled oats, nuts, seeds, and honey baked until crispy.",
  lasagna:  "A layered Italian oven dish of wide pasta sheets with meat sauce, ricotta, and melted cheese.",
  lettuce:  "A leafy green vegetable that forms the crisp, mild base of most green salads.",
  mustard:  "A tangy condiment made from ground mustard seeds with a sharp, nose-tingling flavor.",
  oatmeal:  "A warm, comforting breakfast porridge made from rolled or steel-cut whole oats.",
  pancake:  "A flat, round cake made from a simple batter, cooked in a buttered pan until golden.",
  paprika:  "A bright red spice made from dried ground peppers, essential in Hungarian goulash and Spanish cuisine.",
  parsley:  "A bright green herb with a fresh, clean, slightly bitter flavor used widely as a garnish.",
  poultry:  "Domesticated birds including chicken, turkey, and duck raised for their meat or eggs.",
  pretzel:  "A twisted bread snack seasoned with coarse salt and baked golden, originally from Germany.",
  pudding:  "A creamy, often sweet dessert or thick savory dish cooked by steaming or baking.",
  saffron:  "The world's most expensive spice by weight, harvested by hand from the stigmas of crocus flowers.",
  sardine:  "A small, oily fish eaten fresh or canned, exceptionally rich in omega-3 fatty acids.",
  sausage:  "Seasoned ground meat packed into a casing, a staple at breakfasts and barbecues worldwide.",
  seafood:  "Edible marine life including fish, shrimp, crab, lobster, and various shellfish.",
  sherbet:  "A tart, fruity partially frozen dessert containing a small amount of dairy.",
  sirloin:  "A premium cut of beef from the upper back of the animal, celebrated for its flavor.",
  souffle:  "A light, airy French baked dish that rises dramatically in the oven from beaten egg whites.",
  spinach:  "A dark leafy green vegetable exceptionally rich in iron, vitamins, and minerals.",
  strudel:  "A Central European pastry of paper-thin dough tightly rolled around a sweet apple filling.",
  tapioca:  "Small starch pearls made from cassava root, used in puddings and bubble tea drinks.",
  truffle:  "A prized subterranean fungus with an intensely earthy, musky aroma and extraordinary rarity.",
  vanilla:  "The world's most popular flavor, extracted from the cured pod of a tropical orchid vine.",
  vinegar:  "An acidic liquid produced by fermenting alcohol, used in dressings, marinades, and pickling.",
  allspice: "A dried berry whose single flavor remarkably combines hints of cinnamon, cloves, and nutmeg.",
  barbecue: "A cooking method of smoking meat low and slow over indirect heat for hours at a time.",
  baguette: "A long, thin French bread known for its shatteringly crisp crust and chewy, open crumb.",
  broccoli: "A green cruciferous vegetable with dense, nutritious florets eaten raw or cooked.",
  cinnamon: "A warm, sweet-spicy bark spice used in baking, beverages, and savory dishes worldwide.",
  coleslaw: "A salad of finely shredded raw cabbage and carrot dressed with mayonnaise or vinegar.",
  couscous: "Tiny steamed semolina granules from North Africa, traditionally served alongside stews.",
  cucumber: "A cool, mild, crunchy vegetable with very high water content, popular raw or pickled.",
  eggplant: "A purple-skinned vegetable with spongy flesh that soaks up sauces and flavors beautifully.",
  gazpacho: "A refreshing chilled Spanish soup blended from raw ripe tomatoes and summer vegetables.",
  mackerel: "An oily, strongly flavored ocean fish with firm flesh that is high in omega-3 fatty acids.",
  meatball: "A round ball of seasoned ground meat, classically served in tomato sauce over pasta.",
  molasses: "A thick, dark, bittersweet syrup that is a byproduct of the sugar-refining process.",
  mushroom: "An edible fungus with a deep, savory umami flavor used across a vast range of cuisines.",
  parmesan: "A hard, aged Italian cheese with a nutty, salty, granular character, grated over pasta.",
  plantain: "A starchy, banana-like fruit cooked as a vegetable across tropical cuisines when unripe.",
  porridge: "A warm cereal dish of grains simmered in water or milk, a nourishing breakfast worldwide.",
  rosemary: "An aromatic evergreen Mediterranean herb with needle-like leaves used in roasting and bread.",
  tarragon: "A slender French herb with a subtle anise-like flavor used in classic béarnaise sauce.",
  tiramisu: "An Italian dessert of espresso-soaked ladyfingers layered with sweetened mascarpone cream.",
  turmeric: "A bright golden-yellow spice related to ginger with an earthy flavor and noted health properties.",
  zucchini: "A mild, tender summer squash used in salads, stir-fries, pasta, and even baked goods.",
};

// ─── Config ────────────────────────────────────────────────────────────────────

export const CATEGORY_CONFIG: Record<Category, CategoryConfig> = {
  general: {
    label: "General",
    description: "Everyday English words",
    words: wordList,
    wordDescriptions: {},
  },
  chess: {
    label: "Chess",
    description: "Chess pieces, tactics & strategy",
    words: chessWords,
    wordDescriptions: chessDescriptions,
  },
  animals: {
    label: "Animals",
    description: "Creatures from around the world",
    words: animalWords,
    wordDescriptions: animalDescriptions,
  },
  food: {
    label: "Food",
    description: "Ingredients, dishes & flavors",
    words: foodWords,
    wordDescriptions: foodDescriptions,
  },
};

export const CATEGORIES = Object.keys(CATEGORY_CONFIG) as Category[];

export const DEFAULT_CATEGORY: Category = "general";

export function getCategoryWords(category: Category): string[] {
  return CATEGORY_CONFIG[category].words;
}

export function getWordDescription(category: Category, word: string): string | undefined {
  const desc = CATEGORY_CONFIG[category].wordDescriptions[word.toLowerCase()];
  return desc || undefined;
}
